<section class="page-head">
    <div>
        <h1>Setting / Backup</h1>
        <small>Create, download, and restore complete site backups from a dedicated page.</small>
    </div>
</section>

<?php require __DIR__ . '/partials/nav.php'; ?>

<div class="settings-page-grid">
    <section class="card">
        <div class="card-h">
            <div>
                <h2>Create Full Backup</h2>
                <small>The archive includes application files, installer files, the environment file, and a full MySQL dump.</small>
            </div>
            <span class="badge <?= e(($zipAvailable ?? false) ? 'green' : 'red') ?>"><?= ($zipAvailable ?? false) ? 'ZIP Ready' : 'ZIP Missing' ?></span>
        </div>
        <div class="card-b stack-gap">
            <div class="notice">
                Runtime logs and session files are excluded intentionally so the generated backup is smaller and safer to restore.
            </div>
            <form method="post" action="<?= e(base_url('/settings/backup/create')) ?>" class="stack-gap-sm">
                <?= App\Core\Csrf::field() ?>
                <div class="field">
                    <label>Backup label</label>
                    <input type="text" name="label" value="manual-backup" placeholder="manual-backup">
                </div>
                <button type="submit" class="btn" <?= ($zipAvailable ?? false) ? '' : 'disabled' ?>>Create Backup Now</button>
            </form>
        </div>
    </section>

    <section class="card">
        <div class="card-h">
            <div>
                <h2>Restore from Uploaded ZIP</h2>
                <small>Upload a backup ZIP generated by this system and restore it directly.</small>
            </div>
        </div>
        <div class="card-b stack-gap">
            <div class="alert">
                A safety backup is created automatically before each restore. Restoring overwrites current application files and database content.
            </div>
            <form method="post" action="<?= e(base_url('/settings/backup/restore-upload')) ?>" enctype="multipart/form-data" class="stack-gap-sm">
                <?= App\Core\Csrf::field() ?>
                <div class="field">
                    <label>Backup ZIP file</label>
                    <input type="file" name="backup_zip" accept=".zip" required>
                </div>
                <button type="submit" class="btn secondary" onclick="return confirm('Restore this backup ZIP now? This will replace the current database and application files.')" <?= ($zipAvailable ?? false) ? '' : 'disabled' ?>>Upload & Restore</button>
            </form>
        </div>
    </section>
</div>

<section class="card" style="margin-top:12px;">
    <div class="card-h">
        <div>
            <h2>Available Backups</h2>
            <small>Download or restore any backup generated on this server.</small>
        </div>
    </div>
    <div class="card-b">
        <div class="table-wrap">
            <table class="table">
                <thead>
                <tr>
                    <th>Label</th>
                    <th>Created At</th>
                    <th>Mode</th>
                    <th>Size</th>
                    <th>Archive</th>
                    <th style="width: 220px;">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php if (($backups ?? []) === []): ?>
                    <tr><td colspan="6">No backup archives found yet.</td></tr>
                <?php else: ?>
                    <?php foreach ($backups as $backup): ?>
                        <tr>
                            <td>
                                <strong><?= e($backup['label'] ?? 'backup') ?></strong><br>
                                <small><?= e($backup['id'] ?? '') ?></small>
                            </td>
                            <td class="dt"><?= e(date_display($backup['created_at'] ?? null, 'Y-m-d H:i')) ?></td>
                            <td><span class="badge blue"><?= e(ucfirst((string) ($backup['mode'] ?? 'manual'))) ?></span></td>
                            <td><?= e(format_bytes((int) ($backup['size_bytes'] ?? 0))) ?></td>
                            <td><?= e($backup['file_name'] ?? '') ?></td>
                            <td>
                                <div class="row-actions-tight">
                                    <a href="<?= e($backup['download_url'] ?? '#') ?>" class="btn secondary btn-sm">Download</a>
                                    <form method="post" action="<?= e(base_url('/settings/backup/restore?id=' . urlencode((string) ($backup['id'] ?? '')))) ?>" onsubmit="return confirm('Restore this backup now? The current database and application files will be replaced.')">
                                        <?= App\Core\Csrf::field() ?>
                                        <button type="submit" class="btn btn-sm">Restore</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
