SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `schema_migrations`;DROP TABLE IF EXISTS `bank_accounts`;DROP TABLE IF EXISTS `banking_transactions`;DROP TABLE IF EXISTS `categories`;DROP TABLE IF EXISTS `currencies`;DROP TABLE IF EXISTS `customer_documents`;DROP TABLE IF EXISTS `customers`;DROP TABLE IF EXISTS `inventory_receipt_items`;DROP TABLE IF EXISTS `inventory_receipts`;DROP TABLE IF EXISTS `media_library`;DROP TABLE IF EXISTS `products`;DROP TABLE IF EXISTS `purchase_items`;DROP TABLE IF EXISTS `purchase_payments`;DROP TABLE IF EXISTS `purchase_return_items`;DROP TABLE IF EXISTS `purchase_returns`;DROP TABLE IF EXISTS `purchases`;DROP TABLE IF EXISTS `sale_items`;DROP TABLE IF EXISTS `sale_receipts`;DROP TABLE IF EXISTS `sales`;DROP TABLE IF EXISTS `stock_movements`;DROP TABLE IF EXISTS `suppliers`;DROP TABLE IF EXISTS `units`;DROP TABLE IF EXISTS `users`;DROP TABLE IF EXISTS `warehouse_movements`;DROP TABLE IF EXISTS `warehouse_stocks`;DROP TABLE IF EXISTS `warehouses`;


CREATE TABLE `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `slug` varchar(150) NOT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_categories_name` (`name`),
  UNIQUE KEY `uq_categories_slug` (`slug`),
  KEY `idx_categories_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `currencies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `code` varchar(10) NOT NULL,
  `symbol` varchar(16) NOT NULL,
  `rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_currencies_name` (`name`),
  UNIQUE KEY `uq_currencies_code` (`code`),
  KEY `idx_currencies_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customer_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `customer_id` bigint(20) unsigned NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_ext` varchar(20) DEFAULT NULL,
  `mime_type` varchar(120) DEFAULT NULL,
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_customer_documents_customer` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(60) NOT NULL,
  `customer_type` enum('business','individual') NOT NULL DEFAULT 'individual',
  `company_name` varchar(160) DEFAULT NULL,
  `person_name` varchar(160) DEFAULT NULL,
  `name` varchar(160) NOT NULL,
  `mobile` varchar(60) DEFAULT NULL,
  `phone` varchar(60) DEFAULT NULL,
  `email` varchar(190) DEFAULT NULL,
  `trn_number` varchar(120) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `profile_image_path` varchar(255) DEFAULT NULL,
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `country_code` varchar(12) DEFAULT NULL,
  `country_name` varchar(120) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_customers_name` (`name`),
  KEY `idx_customers_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `media_library` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `path` varchar(255) NOT NULL,
  `title` varchar(190) DEFAULT NULL,
  `alt_text` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `path` (`path`),
  KEY `idx_media_library_path` (`path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `products` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(60) NOT NULL,
  `name` varchar(190) NOT NULL,
  `item_type` enum('inventory','non_inventory','service') NOT NULL DEFAULT 'inventory',
  `category_id` bigint(20) unsigned DEFAULT NULL,
  `category` varchar(120) DEFAULT NULL,
  `unit_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(50) NOT NULL DEFAULT 'pcs',
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `price_currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `image_path` varchar(255) DEFAULT NULL,
  `purchase_price_display` decimal(14,2) NOT NULL DEFAULT 0.00,
  `sale_price_display` decimal(14,2) NOT NULL DEFAULT 0.00,
  `purchase_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `sale_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `carton_length_cm` decimal(14,2) NOT NULL DEFAULT 0.00,
  `carton_width_cm` decimal(14,2) NOT NULL DEFAULT 0.00,
  `carton_height_cm` decimal(14,2) NOT NULL DEFAULT 0.00,
  `gross_weight_kg` decimal(14,3) NOT NULL DEFAULT 0.000,
  `cbm_per_carton` decimal(14,6) NOT NULL DEFAULT 0.000000,
  `units_per_box` decimal(14,2) NOT NULL DEFAULT 1.00,
  `min_stock` decimal(14,2) NOT NULL DEFAULT 0.00,
  `current_stock` decimal(14,2) NOT NULL DEFAULT 0.00,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_products_name` (`name`),
  KEY `idx_products_status` (`status`),
  KEY `idx_products_stock` (`current_stock`,`min_stock`),
  KEY `idx_products_item_type` (`item_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `suppliers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(60) NOT NULL,
  `name` varchar(160) NOT NULL,
  `mobile` varchar(60) DEFAULT NULL,
  `phone` varchar(60) DEFAULT NULL,
  `email` varchar(190) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_suppliers_name` (`name`),
  KEY `idx_suppliers_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `units` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `code` varchar(30) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_units_name` (`name`),
  UNIQUE KEY `uq_units_code` (`code`),
  KEY `idx_units_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `email` varchar(190) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL DEFAULT 'admin',
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `permissions` longtext DEFAULT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(45) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `warehouses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(60) NOT NULL,
  `name` varchar(160) NOT NULL,
  `location` varchar(190) DEFAULT NULL,
  `manager_name` varchar(120) DEFAULT NULL,
  `phone` varchar(60) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_warehouses_code` (`code`),
  KEY `idx_warehouses_status` (`status`),
  KEY `idx_warehouses_default` (`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bank_accounts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(60) NOT NULL,
  `bank_name` varchar(160) NOT NULL,
  `account_name` varchar(160) NOT NULL,
  `account_type` enum('bank','cash','wallet') NOT NULL DEFAULT 'bank',
  `account_number` varchar(80) DEFAULT NULL,
  `iban` varchar(80) DEFAULT NULL,
  `swift_code` varchar(40) DEFAULT NULL,
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `opening_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `opening_balance_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `opening_balance_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `current_balance_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `current_balance_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `notes` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `fk_bank_accounts_user` (`created_by`),
  KEY `idx_bank_accounts_status` (`status`),
  KEY `idx_bank_accounts_currency` (`currency_id`),
  KEY `idx_bank_accounts_type` (`account_type`),
  CONSTRAINT `fk_bank_accounts_currency` FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_bank_accounts_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchases` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `supplier_id` bigint(20) unsigned NOT NULL,
  `invoice_no` varchar(80) NOT NULL,
  `invoice_date` date NOT NULL,
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `currency_symbol` varchar(16) NOT NULL DEFAULT 'د.إ',
  `currency_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `final_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `discount_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `final_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `receipt_status` enum('pending','partial','received') NOT NULL DEFAULT 'pending',
  `return_status` enum('none','partial','returned') NOT NULL DEFAULT 'none',
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_no` (`invoice_no`),
  KEY `fk_purchases_user` (`created_by`),
  KEY `idx_purchases_invoice_date` (`invoice_date`),
  KEY `idx_purchases_supplier` (`supplier_id`),
  KEY `fk_purchases_currency` (`currency_id`),
  CONSTRAINT `fk_purchases_currency` FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_purchases_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`),
  CONSTRAINT `fk_purchases_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `customer_id` bigint(20) unsigned NOT NULL,
  `warehouse_id` bigint(20) unsigned DEFAULT NULL,
  `invoice_no` varchar(80) NOT NULL,
  `invoice_date` date NOT NULL,
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `currency_symbol` varchar(16) NOT NULL DEFAULT 'د.إ',
  `currency_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `final_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `discount_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `final_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payment_status` enum('paid','pending') NOT NULL DEFAULT 'paid',
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_no` (`invoice_no`),
  KEY `fk_sales_user` (`created_by`),
  KEY `idx_sales_invoice_date` (`invoice_date`),
  KEY `idx_sales_customer` (`customer_id`),
  KEY `idx_sales_status` (`payment_status`),
  KEY `fk_sales_currency` (`currency_id`),
  CONSTRAINT `fk_sales_currency` FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sales_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `fk_sales_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_movements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` bigint(20) unsigned NOT NULL,
  `type` enum('purchase','sale','adjustment','receipt','purchase_return') NOT NULL,
  `ref_type` varchar(50) NOT NULL,
  `ref_id` bigint(20) unsigned DEFAULT NULL,
  `qty_in` decimal(14,2) NOT NULL DEFAULT 0.00,
  `qty_out` decimal(14,2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14,2) NOT NULL DEFAULT 0.00,
  `note` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_stock_movements_product` (`product_id`),
  KEY `idx_stock_movements_type` (`type`),
  KEY `idx_stock_movements_created` (`created_at`),
  CONSTRAINT `fk_stock_movements_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `warehouse_movements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `warehouse_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `type` enum('receipt','sale','adjustment','return') NOT NULL,
  `ref_type` varchar(50) NOT NULL,
  `ref_id` bigint(20) unsigned DEFAULT NULL,
  `qty_in` decimal(14,2) NOT NULL DEFAULT 0.00,
  `qty_out` decimal(14,2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14,2) NOT NULL DEFAULT 0.00,
  `note` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_warehouse_movements_warehouse` (`warehouse_id`),
  KEY `idx_warehouse_movements_product` (`product_id`),
  KEY `idx_warehouse_movements_created` (`created_at`),
  KEY `fk_warehouse_movements_user` (`created_by`),
  CONSTRAINT `fk_warehouse_movements_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_warehouse_movements_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_warehouse_movements_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `warehouse_stocks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `warehouse_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_warehouse_product` (`warehouse_id`,`product_id`),
  KEY `idx_warehouse_stocks_product` (`product_id`),
  CONSTRAINT `fk_warehouse_stocks_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_warehouse_stocks_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `banking_transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `bank_account_id` bigint(20) unsigned NOT NULL,
  `related_bank_account_id` bigint(20) unsigned DEFAULT NULL,
  `txn_date` date NOT NULL,
  `type` enum('deposit','withdrawal','adjustment_in','adjustment_out','transfer_in','transfer_out','purchase_payment','sale_receipt') NOT NULL,
  `reference_no` varchar(80) DEFAULT NULL,
  `counterparty` varchar(160) DEFAULT NULL,
  `amount_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `exchange_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `amount_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `balance_after_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `balance_after_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `note` text DEFAULT NULL,
  `transfer_group` varchar(80) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_banking_transactions_related_account` (`related_bank_account_id`),
  KEY `fk_banking_transactions_user` (`created_by`),
  KEY `idx_banking_transactions_date` (`txn_date`),
  KEY `idx_banking_transactions_type` (`type`),
  KEY `idx_banking_transactions_account` (`bank_account_id`),
  KEY `idx_banking_transactions_transfer_group` (`transfer_group`),
  CONSTRAINT `fk_banking_transactions_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_banking_transactions_related_account` FOREIGN KEY (`related_bank_account_id`) REFERENCES `bank_accounts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_banking_transactions_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `inventory_receipts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_id` bigint(20) unsigned NOT NULL,
  `warehouse_id` bigint(20) unsigned NOT NULL,
  `receipt_no` varchar(80) NOT NULL,
  `receipt_date` date NOT NULL,
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_receipts_no` (`receipt_no`),
  KEY `idx_inventory_receipts_purchase` (`purchase_id`),
  KEY `idx_inventory_receipts_warehouse` (`warehouse_id`),
  KEY `fk_inventory_receipts_user` (`created_by`),
  CONSTRAINT `fk_inventory_receipts_purchase` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_receipts_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_inventory_receipts_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `display_qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `pricing_unit` varchar(20) NOT NULL DEFAULT 'unit',
  `units_per_box` decimal(14,2) NOT NULL DEFAULT 1.00,
  `qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `received_qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `returned_qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_items_purchase` (`purchase_id`),
  KEY `idx_purchase_items_product` (`product_id`),
  CONSTRAINT `fk_purchase_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_purchase_items_purchase` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_id` bigint(20) unsigned NOT NULL,
  `supplier_id` bigint(20) unsigned NOT NULL,
  `bank_account_id` bigint(20) unsigned NOT NULL,
  `payment_no` varchar(80) NOT NULL,
  `payment_date` date NOT NULL,
  `amount_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `exchange_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `amount_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `reference_no` varchar(80) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_no` (`payment_no`),
  KEY `fk_purchase_payments_user` (`created_by`),
  KEY `idx_purchase_payments_purchase` (`purchase_id`),
  KEY `idx_purchase_payments_supplier` (`supplier_id`),
  KEY `idx_purchase_payments_bank_account` (`bank_account_id`),
  KEY `idx_purchase_payments_payment_date` (`payment_date`),
  CONSTRAINT `fk_purchase_payments_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`),
  CONSTRAINT `fk_purchase_payments_purchase` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_purchase_payments_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_purchase_payments_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_returns` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_id` bigint(20) unsigned NOT NULL,
  `warehouse_id` bigint(20) unsigned NOT NULL,
  `return_no` varchar(80) NOT NULL,
  `return_date` date NOT NULL,
  `currency_id` bigint(20) unsigned DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `currency_symbol` varchar(16) NOT NULL DEFAULT 'د.إ',
  `currency_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `total_qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_amount_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `reason` varchar(255) NOT NULL,
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_purchase_returns_no` (`return_no`),
  KEY `idx_purchase_returns_purchase` (`purchase_id`),
  KEY `idx_purchase_returns_warehouse` (`warehouse_id`),
  KEY `idx_purchase_returns_date` (`return_date`),
  KEY `fk_purchase_returns_user` (`created_by`),
  CONSTRAINT `fk_purchase_returns_purchase` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_purchase_returns_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_purchase_returns_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sale_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `display_qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `pricing_unit` varchar(20) NOT NULL DEFAULT 'unit',
  `units_per_box` decimal(14,2) NOT NULL DEFAULT 1.00,
  `qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `cost_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sale_items_sale` (`sale_id`),
  KEY `idx_sale_items_product` (`product_id`),
  CONSTRAINT `fk_sale_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_sale_items_sale` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sale_receipts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` bigint(20) unsigned NOT NULL,
  `customer_id` bigint(20) unsigned NOT NULL,
  `bank_account_id` bigint(20) unsigned NOT NULL,
  `receipt_no` varchar(80) NOT NULL,
  `receipt_date` date NOT NULL,
  `amount_currency` decimal(18,2) NOT NULL DEFAULT 0.00,
  `currency_code` varchar(10) NOT NULL DEFAULT 'AED',
  `exchange_rate_to_aed` decimal(18,8) NOT NULL DEFAULT 1.00000000,
  `amount_aed` decimal(18,2) NOT NULL DEFAULT 0.00,
  `reference_no` varchar(80) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `receipt_no` (`receipt_no`),
  KEY `fk_sale_receipts_user` (`created_by`),
  KEY `idx_sale_receipts_sale` (`sale_id`),
  KEY `idx_sale_receipts_customer` (`customer_id`),
  KEY `idx_sale_receipts_bank_account` (`bank_account_id`),
  KEY `idx_sale_receipts_receipt_date` (`receipt_date`),
  CONSTRAINT `fk_sale_receipts_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`),
  CONSTRAINT `fk_sale_receipts_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sale_receipts_sale` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sale_receipts_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `inventory_receipt_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `receipt_id` bigint(20) unsigned NOT NULL,
  `purchase_item_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_cost_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_receipt_items_receipt` (`receipt_id`),
  KEY `idx_inventory_receipt_items_purchase_item` (`purchase_item_id`),
  KEY `idx_inventory_receipt_items_product` (`product_id`),
  CONSTRAINT `fk_inventory_receipt_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_inventory_receipt_items_purchase_item` FOREIGN KEY (`purchase_item_id`) REFERENCES `purchase_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_receipt_items_receipt` FOREIGN KEY (`receipt_id`) REFERENCES `inventory_receipts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_return_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_return_id` bigint(20) unsigned NOT NULL,
  `purchase_item_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `qty` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `unit_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_price_aed` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_return_items_return` (`purchase_return_id`),
  KEY `idx_purchase_return_items_purchase_item` (`purchase_item_id`),
  KEY `idx_purchase_return_items_product` (`product_id`),
  CONSTRAINT `fk_purchase_return_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `fk_purchase_return_items_purchase_item` FOREIGN KEY (`purchase_item_id`) REFERENCES `purchase_items` (`id`),
  CONSTRAINT `fk_purchase_return_items_return` FOREIGN KEY (`purchase_return_id`) REFERENCES `purchase_returns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
