<?php

declare(strict_types=1);

namespace App\Core;

use PDO;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RuntimeException;
use ZipArchive;

final class BackupManager
{
    private const MANIFEST_TYPE = 'lca_backup';

    public function __construct(private readonly ?PDO $pdo = null)
    {
    }

    public function listBackups(): array
    {
        ensure_directory($this->backupsDir());

        $items = [];
        foreach (glob($this->backupsDir() . '/*.json') ?: [] as $manifestPath) {
            $data = json_decode((string) file_get_contents($manifestPath), true);
            if (!is_array($data)) {
                continue;
            }

            $zipPath = $this->backupsDir() . '/' . ($data['file_name'] ?? '');
            if (!is_file($zipPath)) {
                continue;
            }

            $data['size_bytes'] = filesize($zipPath) ?: ($data['size_bytes'] ?? 0);
            $data['download_url'] = base_url('/settings/backup/download?id=' . urlencode((string) ($data['id'] ?? '')));
            $items[] = $data;
        }

        usort($items, static fn (array $a, array $b): int => strcmp((string) ($b['created_at'] ?? ''), (string) ($a['created_at'] ?? '')));

        return $items;
    }

    public function createFullBackup(string $label = 'manual-backup', array $meta = []): array
    {
        $this->ensureZipSupport();
        ensure_directory($this->backupsDir());

        $timestamp = date('Ymd-His');
        $id = $timestamp . '-' . $this->slug($label);
        $zipPath = $this->backupsDir() . '/' . $id . '.zip';

        $manifest = [
            'type' => self::MANIFEST_TYPE,
            'id' => $id,
            'label' => $label,
            'created_at' => date(DATE_ATOM),
            'created_by' => $meta['created_by'] ?? 'system',
            'mode' => $meta['mode'] ?? 'manual',
            'app_name' => config('app.name', 'LCA'),
            'app_url' => config('app.url', detect_app_url()),
            'version' => '1.0.1',
            'contents' => [
                'database_dump' => true,
                'application_files' => true,
                'env_file' => true,
                'runtime_logs' => false,
                'runtime_sessions' => false,
            ],
            'notes' => 'Generated by the LCA backup manager.',
        ];

        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('The backup archive could not be created.');
        }

        $zip->addFromString('manifest.json', json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        $zip->addFromString('db/database.sql', $this->exportDatabaseSql());

        foreach ($this->projectFiles() as [$absolutePath, $relativePath]) {
            $zip->addFile($absolutePath, 'files/' . $relativePath);
        }

        $zip->close();

        $manifest['file_name'] = basename($zipPath);
        $manifest['size_bytes'] = filesize($zipPath) ?: 0;

        file_put_contents(
            $this->backupsDir() . '/' . $id . '.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );

        return $manifest;
    }

    public function downloadPath(string $id): string
    {
        $manifest = $this->readManifest($id);
        $path = $this->backupsDir() . '/' . ($manifest['file_name'] ?? '');

        if (!is_file($path)) {
            throw new RuntimeException('The selected backup archive could not be found.');
        }

        return $path;
    }

    public function restoreById(string $id, array $meta = []): array
    {
        return $this->restoreArchive($this->downloadPath($id), $meta);
    }

    public function restoreArchive(string $archivePath, array $meta = []): array
    {
        $this->ensureZipSupport();

        if (!is_file($archivePath)) {
            throw new RuntimeException('The selected backup file does not exist.');
        }

        $safetyBackup = $this->createFullBackup('pre-restore-safety', [
            'created_by' => $meta['created_by'] ?? 'system',
            'mode' => 'pre-restore',
        ]);

        $tempDir = storage_path('app/restore-' . date('Ymd-His') . '-' . bin2hex(random_bytes(3)));
        ensure_directory($tempDir);

        $zip = new ZipArchive();
        if ($zip->open($archivePath) !== true) {
            throw new RuntimeException('The backup archive could not be opened.');
        }

        if (!$zip->extractTo($tempDir)) {
            $zip->close();
            throw new RuntimeException('The backup archive could not be extracted.');
        }
        $zip->close();

        $manifestPath = $tempDir . '/manifest.json';
        $filesRoot = $tempDir . '/files';
        $databasePath = $tempDir . '/db/database.sql';

        if (!is_file($manifestPath) || !is_dir($filesRoot) || !is_file($databasePath)) {
            throw new RuntimeException('This backup archive is not a valid LCA backup package.');
        }

        $manifest = json_decode((string) file_get_contents($manifestPath), true);
        if (!is_array($manifest) || ($manifest['type'] ?? '') !== self::MANIFEST_TYPE) {
            throw new RuntimeException('The backup manifest is missing or invalid.');
        }

        $this->importDatabaseSql((string) file_get_contents($databasePath));
        $copiedFiles = $this->copyTree($filesRoot, project_path(), true);

        return [
            'restored_backup' => $manifest['id'] ?? basename($archivePath),
            'files_applied' => $copiedFiles,
            'safety_backup_id' => $safetyBackup['id'] ?? null,
        ];
    }

    private function exportDatabaseSql(): string
    {
        $pdo = $this->pdo ?? Database::connection();
        $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) ?: [];

        $sql = [];
        $sql[] = '-- LCA Database Backup';
        $sql[] = '-- Generated at ' . date(DATE_ATOM);
        $sql[] = 'SET FOREIGN_KEY_CHECKS=0;';
        $sql[] = '';

        foreach ($tables as $table) {
            $tableName = (string) $table;
            $create = $pdo->query('SHOW CREATE TABLE `' . str_replace('`', '``', $tableName) . '`')->fetch(PDO::FETCH_NUM);
            if (!$create || !isset($create[1])) {
                continue;
            }

            $sql[] = 'DROP TABLE IF EXISTS `' . $tableName . '`;';
            $sql[] = (string) $create[1] . ';';
            $sql[] = '';

            $rows = $pdo->query('SELECT * FROM `' . str_replace('`', '``', $tableName) . '`')->fetchAll(PDO::FETCH_ASSOC);
            if ($rows === []) {
                continue;
            }

            $columns = array_keys($rows[0]);
            $columnSql = '`' . implode('`, `', array_map(static fn (string $column): string => str_replace('`', '``', $column), $columns)) . '`';

            $chunk = [];
            foreach ($rows as $row) {
                $values = [];
                foreach ($columns as $column) {
                    $values[] = $this->sqlValue($pdo, $row[$column] ?? null);
                }
                $chunk[] = '(' . implode(', ', $values) . ')';

                if (count($chunk) >= 100) {
                    $sql[] = 'INSERT INTO `' . $tableName . '` (' . $columnSql . ') VALUES' . PHP_EOL . implode(',' . PHP_EOL, $chunk) . ';';
                    $sql[] = '';
                    $chunk = [];
                }
            }

            if ($chunk !== []) {
                $sql[] = 'INSERT INTO `' . $tableName . '` (' . $columnSql . ') VALUES' . PHP_EOL . implode(',' . PHP_EOL, $chunk) . ';';
                $sql[] = '';
            }
        }

        $sql[] = 'SET FOREIGN_KEY_CHECKS=1;';
        $sql[] = '';

        return implode(PHP_EOL, $sql);
    }

    private function importDatabaseSql(string $sql): void
    {
        $pdo = $this->pdo ?? Database::connection();
        foreach (split_sql_statements($sql) as $statement) {
            if (trim($statement) === '') {
                continue;
            }

            $pdo->exec($statement);
        }
    }

    private function copyTree(string $source, string $destination, bool $overwrite = false): int
    {
        $count = 0;
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($source, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($iterator as $item) {
            $absolute = $item->getPathname();
            $relative = ltrim(str_replace('\\', '/', substr($absolute, strlen($source))), '/');
            if ($relative === '' || $this->shouldSkipRuntimePath($relative)) {
                continue;
            }

            $target = $destination . '/' . $relative;

            if ($item->isDir()) {
                ensure_directory($target);
                continue;
            }

            ensure_directory(dirname($target));
            if (!$overwrite && is_file($target)) {
                continue;
            }

            if (!copy($absolute, $target)) {
                throw new RuntimeException('Could not restore file: ' . $relative);
            }
            $count++;
        }

        return $count;
    }

    private function projectFiles(): iterable
    {
        $root = project_path();
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($iterator as $file) {
            if (!$file->isFile()) {
                continue;
            }

            $absolute = $file->getPathname();
            $relative = ltrim(str_replace('\\', '/', substr($absolute, strlen($root))), '/');

            if ($this->shouldExcludeFromBackup($relative)) {
                continue;
            }

            yield [$absolute, $relative];
        }
    }

    private function shouldExcludeFromBackup(string $relativePath): bool
    {
        $relativePath = ltrim(str_replace('\\', '/', $relativePath), '/');

        $excluded = [
            'storage/app/backups/',
            'storage/app/update-packages/',
            'storage/app/update-staging/',
            'storage/app/restore-',
            'storage/logs/',
            'storage/sessions/',
            '.git/',
        ];

        foreach ($excluded as $prefix) {
            if (str_starts_with($relativePath, $prefix)) {
                return true;
            }
        }

        return false;
    }

    private function shouldSkipRuntimePath(string $relativePath): bool
    {
        $relativePath = ltrim(str_replace('\\', '/', $relativePath), '/');
        $protected = [
            'storage/app/backups/',
            'storage/app/update-packages/',
            'storage/app/update-staging/',
            'storage/logs/',
            'storage/sessions/',
        ];

        foreach ($protected as $prefix) {
            if (str_starts_with($relativePath, $prefix)) {
                return true;
            }
        }

        return false;
    }

    private function sqlValue(PDO $pdo, mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        return $pdo->quote((string) $value);
    }

    private function readManifest(string $id): array
    {
        $path = $this->backupsDir() . '/' . basename($id) . '.json';
        if (!is_file($path)) {
            throw new RuntimeException('The selected backup could not be found.');
        }

        $data = json_decode((string) file_get_contents($path), true);
        if (!is_array($data)) {
            throw new RuntimeException('The selected backup manifest is invalid.');
        }

        return $data;
    }

    private function backupsDir(): string
    {
        $path = storage_path('app/backups');
        ensure_directory($path);
        return $path;
    }

    private function ensureZipSupport(): void
    {
        if (!class_exists(ZipArchive::class)) {
            throw new RuntimeException('The PHP ZipArchive extension is required for backup and restore.');
        }
    }

    private function slug(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9]+/i', '-', $value) ?: 'backup';
        return trim($value, '-') ?: 'backup';
    }
}
